### ISSUE TITLE
MVP Review

### ISSUE THREAD

**Issue by danemauland** [lrharris215/coal#1]
Hey Lane! Great work on your MVP page. It's clear you put a lot of thought into this and made sure to think through your project. My feedback on this consists of just minor corrections/suggestions:

'-Formatting is sufficient but consider bolding the MVP names, see here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
Hosting on Heroku
-Typo here in completion date--will be hosted on Monday (3/15)
Reviews and Reactions
-Consider moving reactions to a bonus feature just to give yourself a little more room on the project.
-Add in a bullet point akin to "users can view reviews on games product pages for that game"

Completion dates
Your production README will take only a few hours to make and you'll have time to do than on Friday. I'd recommend spreading the dates for the other MVPs out a little bit to give yourself more padding throughout the project. The final decision is up to you, but I'd recommend adding a day to User Auth (since it also includes creating the splash page)

**Comment by lrharris215** [comment]
Made the fixes to the MVP list
