### ISSUE TITLE
PA Review: Shopping Cart

### ISSUE THREAD

**Issue by lrharris215** [lrharris215/coal#10]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by lrharris215** [comment]
Just a note- haven't built the library yet, so there is no visual way to tell that the items are now in your possession, but I've checked the backend and the requests are going through and are being added to the purchases table, at least on the local db, not sure how to look at the heroku database.

**Comment by danemauland** [comment]
Their envelope icon next to the username has a background color different from the navbar
The "Remove" link in the shopping cart is missing an underline/mouse over effects
Review the arrow/display box as discussed

**Comment by lrharris215** [comment]
Ok fixed!

**Comment by danemauland** [comment]
Awesome work!
