### ISSUE TITLE
Schema Review

### ISSUE THREAD

**Issue by danemauland** [lrharris215/coal#2]
Great work on the schema! The overall structure is very solid, I'd just like to see some more of the details fleshed out:

Below each respective table, list which table each foreign key references and the associations for that table (e.g. "has a has-many relationship with games")
Users
-Review having both username/email indexed. If users can log in using either their name or email, then this would be needed, but that seems like something you could wait until you get to your bonus features to implement. I'm not seeing anything else in your MVP list that would require an index on both of these.
Games
-Review the need for an index on title
-take "(in cents)" out of the column name for price and note it below the table
Game-Images
-Figure out why formatting on this table name isn't working
-explain what img_type is/what it's used for

**Comment by lrharris215** [comment]
Fixed formatting, moved reactions to bonus section, added explanations.
