### ISSUE TITLE
Backend Routes Review

### ISSUE THREAD

**Issue by danemauland** [lrharris215/coal#4]
Great work on your backend routes as well!

Users
-I agree that the user show page is unnecessary for this project. you can consider adding it later as a bonus feature, but I would not worry about it for now.
Reactions
-As mentioned in your MVP review, reactions can be a bonus feature, but I think these would make more sense as nested routes

**Comment by lrharris215** [comment]
Deleted the user show page, moved the reaction routes to the bonus and made them nested under reviews. Unsure about the delete route though, reviews/:reviewId/reactions/:reactionId. Are two wildcards possible?

**Comment by lrharris215** [comment]
This is a problem for future Lane, fixed the things I can actually do now.
