### ISSUE TITLE
Final Design Dec Review

### ISSUE THREAD

**Issue by danemauland** [lrharris215/coal#7]
Your design docs are looking great! I consider them essentially done at this point and will need no further review after the below edits, but feel free to update them as the need arises going forward.

MVP List - Bold production README

Sample State - Change your comment regarding tho shopping cart to something akin to "shopping cart will be stored in local storage"

Frontend Routes - Remove ReactionItem from /games/gameId or change the parathesis to "(bonus)"

**Comment by lrharris215** [comment]
Done! Thanks!
